// Code generated by Slice Machine. DO NOT EDIT.

import ContactForm from './ContactForm';
import Image from './Image';
import Menu from './Menu';
import MenuFirstLevel from './MenuFirstLevel';
import Quote from './Quote';
import Text from './Text';

export {
	ContactForm,
	Image,
	Menu,
	MenuFirstLevel,
	Quote,
	Text,
};

export const components = {
	contact_form: ContactForm,
	image: Image,
	menu: Menu,
	menu_first_level: MenuFirstLevel,
	quote: Quote,
	text: Text,
};
