import Head from "next/head";
import { Layout } from "@components/layout";

export default function Home() {
  return (
    <div className="bg-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout items={[]}>dad</Layout>
    </div>
  );
}
